# Generated by Django 5.1.6 on 2025-02-13 21:41

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.TextField()),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('location', models.TextField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
