{
 "title": "Caddy",
 "description": "Monitoring Caddy Server with Grafana.",
 "tags": [ "caddy" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasourceprometheus", "label": "Datasource Prometheus", "query": "prometheus" },
   {
    "name": "host",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=~\"caddy.*\"},instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values({__name__=~\"^caddy.*\", handler=~\".*\"},handler)"
    }
   },
   {
    "name": "site",
    "label": "Host",
    "query": {
     "query": "label_values(caddy_http_requests_total,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Synthesis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[1m])) by (handler)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of requests processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of requests per second (avg 5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[5m])) by (handler)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Status Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}) by (code)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Middleware Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "API REST Caddy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HTTP(S) requests total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Requests In Flight",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(caddy_http_requests_in_flight{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Duration (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(caddy_http_request_duration_seconds_bucket{instance=~\"$host\", handler=~\"$handler\",host=~\"$site\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Median response duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_duration_seconds_bucket{host=~\"$site\"}[5m])))"
    }
   ]
  },
  {
   "title": "Request/Response duration seconds",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Median response size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(caddy_http_response_size_bytes_bucket{instance=~\"$host\",host=~\"$site\"}[5m])))"
    }
   ]
  },
  {
   "title": "Requests by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[1m])) by (code)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Duration (percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$host\",handler=~\"$handler\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$host\",handler=~\"$handler\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$host\",handler=~\"$handler\"}[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(caddy_http_request_duration_seconds_bucket{instance=~\"$host\",handler=~\"$handler\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(caddy_http_request_duration_seconds_count{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}) by (code)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Status Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (caddy_http_request_duration_seconds_count{instance=~\"$host\", handler=~\"$handler\",host=~\"$site\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Middleware Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_request_errors_total{instance=~\"$host\",handler=~\"$handler\",host=~\"$site\"}[5m])*10) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}