# Global config
global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 10m
  external_labels:
    environment: local
    instance: somemachinelol

scrape_configs:
  # Prometheus
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # Postgres
  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis
  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]

  # Celery
  - job_name: celery
    scrape_interval: 15s
    static_configs:
      - targets: ["celery-exporter:9808"]

  # Backend
  - job_name: backend
    static_configs:
      - targets: ["backend:8080"]

  # Caddy
  - job_name: caddy
    static_configs:
      - targets: ["caddy:2019"]
